version: '2.1'

services:
  app:
    restart: always
    build: app/
    volumes:
      - ./app/ :/app/
    extends:
      service: panel
    ports:
      - "80:80"
  panel:
    restart: always
    build: panel/
    volumes:
      - ./panel/ :/panel/
    ports:
      - "8080:8080"