version: '2.1'

services:
  app:
    restart: always
    build: app/
    volumes:
      - ./app/ :/app/
    ports:
      - "80:80"
  mexican:
    restart: always
    build: mexican_web
    volumes:
      - ./mexican_web/ :/mexican_web/
    ports:
      - "8080:8080"